-- EXISE UM PROBLEMA DE REFERENCIA ENTRE AS TABELAS RODADA_JOGADOR E TABELAS ( )... SUAS CHAVES CANDIDATAS
-- SÃO FRÁGEIS (TRÊS TIMES NÃO COINCIDEM: ATLETICO-PR, AMERICA-MG, ATLETICO-MG)...
-- 1. CRIE OS SCRIPTS DML PARA ATUALIZAR OS REGISTROS DA TABELA DE RODADAO_JOGADOR CORRIGINDO ESTA INCONSISTENCIA

UPDATE RODADA_JOGADOR SET  TIME_ID = 'Bahia - BA' WHERE TIME_ID = 'Bahia'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Botafogo - RJ' WHERE TIME_ID = 'Botafogo'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Ceará - CE' WHERE TIME_ID = 'Ceará'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Chapecoense - SC' WHERE TIME_ID = 'Chapecoense'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Corinthians - SP' WHERE TIME_ID = 'Corinthians'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Cruzeiro - MG' WHERE TIME_ID = 'Cruzeiro'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Flamengo - RJ' WHERE TIME_ID = 'Flamengo'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Fluminense - RJ' WHERE TIME_ID = 'Fluminense'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Grêmio - RS' WHERE TIME_ID = 'Grêmio'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Internacional - RS' WHERE TIME_ID = 'Internacional'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Palmeiras - SP' WHERE TIME_ID = 'Palmeiras'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Paraná - PR' WHERE TIME_ID = 'Paraná'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Santos - SP' WHERE TIME_ID = 'Santos'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'São Paulo - SP' WHERE TIME_ID = 'São Paulo'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Sport - PE' WHERE TIME_ID = 'Sport'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Vasco da Gama - RJ' WHERE TIME_ID = 'Vasco'
UPDATE RODADA_JOGADOR SET  TIME_ID = 'Vitória - BA' WHERE TIME_ID = 'Vitória'

-- 2. CRIE INTEGRIDADE REFERENCIAL NO MODELO LEVANDO EM CONSIDERAÇÃO
-- A: UM CLUBE TEM VARIOS JOGADORES EM RODADAS DIFERENTES
-- B: UM JOGADOR PARTICIPA DE VARIAS RODADAS POR UM OU MAIS CLUBES
-- C: UM CLUBE JOGA UMA PARTIDA EM UMA RODADA
-- PERGUNTA: NAO SERÁ POSSIVEL CRIAR REFERENCIA FORTE (PK-FK) ENTRE AS TABELAS TABELAS E RODADA_JOGADOR, POR QUE?

-- 3. RETORNE A QUANTIDADE DE JOGOS POR RODADA DE CADA TIME (INDEPENTENTE SE TIME DA CASA OU FORA)
-- ORDENAR POR RODADA E TIME DE FORMA CRESCENTE



-- 4. RETORNE A QUANTIDADE DE JOGOS POR TIME (INDEPENDENTE DA RODADA)
-- ORDENAR POR TIME DE FORMA CRESCENTE

-- 5. RETORNE A ESCALACAO DE CADA TIME NA RODADA 3, COM OS SEGUINTES DADOS:
-- NOME DO CLUBE, APELIDO DO JOGADOR, POSICAO DO JOGADOR E STATUS DO JOGADOR
-- ORDENE PELO NOME DO CLUBE E APELIDO DO JOGADOR EM ORDEM CRESCENTE

-- 6. RETORNE O(S) JOGADOR(ES) COM MAIOR QUANTIDADE DE GOLS POR RODADA (EM CASO DE EMPATE RETORNE TODOS):
-- RODADA, NOME DO CLUBE, APELIDO DO JOGADOR, GOLS
