-- AC6 --- DEVERÁ SER ENTREGUE HOJE E EM UM ÚNICO SCRIPT
-- 1. INSIRA UM REGISTRO EM CADA TABELA
-- 2. CRIE UM USUARIO COM LOGIN 'EMILIO.MURTA' E SENHA '123456'


INSERT INTO USUARIO (LOGIN, SENHA)
VALUES ('Takai','12345'), 
('Jose','12345'),
('Gustavo','12345'),
('Luiz','456789'),
('EMILIO.MURTA','123456');
SELECT * FROM USUARIO


INSERT INTO COORDENADOR (ID_USUARIO,NOME,EMAIL,CELULAR)
VALUES (3,'Gustavo Luiz','gustavo@gmail','119555623');
SELECT * FROM COORDENADOR

INSERT INTO ALUNO (ID_USUARIO,NOME,EMAIL,CELULAR,RA,FOTO)
VALUES (4,'Luiz','josezinho@gmail','119557723','184556','..'),
(2,'Luiz Souza','Luiz@gmail','119556623','180456','..');
SELECT * FROM ALUNO

INSERT INTO PROFESSOR (ID_USUARIO, NOME, EMAIL, CELULAR, APELIDO)
VALUES (1,'Takai','Takai@gmail','119556624','japa');
SELECT * FROM PROFESSOR

INSERT INTO DISCIPLINA (NOME,PLANO_DE_ENSINO,CARGA_HORARIA,COMPETENCIAS,HABILIDADES,EMENTA,CONTEUDO_PROGRAMATICO,BIBLIOGRAFIA_BASICA,BIBLIOGRAFIA_COMPLEMENTAR,PERCENTUAL_PRATICO,PERCENTUAL_TEORICO,ID_COORDENADOR)
VALUES ('BD2','APRENDER SQL','80','FICAR BOM NA DISCIPLINA','APRIMORAMENTO','QUALQUER COISA','JOIN','ARTICO ACADEMICO','ARTIGO',50,50,1);
SELECT * FROM DISCIPLINA

INSERT INTO CURSO (NOME)
VALUES ('Banco de Dados');
SELECT * FROM CURSO

INSERT INTO DISCIPLINA_OFERTADA(ID_COORDENADOR, DT_INICIO_MATRICULA, DT_FIM_MATRICULA, ID_DISCIPLINA, ID_CURSO, ANO , SEMESTRE , TURMA, ID_PROFESSOR , METODOLOGIA, RECURSOS, CRITERIO_AVALIACAO, PLANO_DE_AULAS)
VALUES	(1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 1), 1,2019,2, 'A',1, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO')

INSERT INTO  SOLICITACAO_MATRICULA(ID_ALUNO, ID_DISCIPLINA_OFERTADA, ID_COORDENADOR)
VALUES (1,1,1)
SELECT * FROM SOLICITACAO_MATRICULA

INSERT INTO ATIVIDADE(TITULO, DESCRICAO, CONTEUDO, TIPO, EXTRAS, ID_PROFESSOR)
VALUES ('AC DIFERENCIADA','DIFICIL','UM AI','RESPOSTA ABERTA','N/A',1);
SELECT * FROM ATIVIDADE

INSERT INTO ATIVIDADE_VINCULADA(ID_ATIVIDADE, ID_PROFESSOR, ID_DISCIPLINA_OFERTADA, ROTULO, STATUS)
VALUES (1,1,1,'TESTE DE HABILIDADES','DISPONIBILIZADA')
SELECT * FROM ATIVIDADE_VINCULADA


INSERT INTO ENTREGA(ID_ALUNO, ID_ATIVIDADE_VINCULADA, TITULO, RESPOSTA, ID_PROFESSOR, NOTA, DT_AVALIACAO, OBS)
VALUES (1,1,'Join', 'Resposta',1,10,GETDATE(),'Quero um deeeezzz')
SELECT * FROM ENTREGA

INSERT INTO MENSAGEM(ID_ALUNO, ID_PROFESSOR, ASSUNTO, REFERENCIA, CONTEUDO, DT_REPOSTA, RESPOSTA)
VALUES (1,1,'Prova','Professor','Não entendi meu 10 errei uma','','Uma ai' )
SELECT * FROM MENSAGEM


-- 3. ATUALIZE A DT_EXPIRACAO DO USUARIO PARA O DIA DE HOJE E A SENHA PARA '654321'

UPDATE USUARIO SET DT_EXPIRACAO = GETDATE(), SENHA = '654321' WHERE ID = 2
select * from usuario

-- 4. CRIE UM PROFESSOR PARA O USUARIO CRIADO (UTILIZE UM SELECT PARA DESCOBRIR O ID DO USUARIO CRIADO)

INSERT INTO PROFESSOR (ID_USUARIO, NOME, EMAIL, CELULAR, APELIDO)
VALUES ((SELECT ID  FROM USUARIO WHERE ID = 5),'Emilio Murta','emilio.murta@gmail','119856624','milho');
SELECT * FROM PROFESSOR

-- 5. GARANTA A EXISTENCIA DE APENAS TRES DISCIPLINAS: 'LP', 'BD2' E 'ESTATISTICA' -- TODAS COM STATUS ABERTA

SELECT * FROM DISCIPLINA

INSERT INTO DISCIPLINA (NOME,PLANO_DE_ENSINO,CARGA_HORARIA,COMPETENCIAS,HABILIDADES,EMENTA,CONTEUDO_PROGRAMATICO,BIBLIOGRAFIA_BASICA,BIBLIOGRAFIA_COMPLEMENTAR,PERCENTUAL_PRATICO,PERCENTUAL_TEORICO,ID_COORDENADOR)
VALUES ('ESTATISTICA','APRENDER ESTATISTICA','80','FICAR BOM NA DISCIPLINA','APRIMORAMENTO','QUALQUER COISA','MATEMATICA','ARTICO ACADEMICO','ARTIGO',50,50,1),
('LP','APRENDER PROGRAMAÇÃO','80','FICAR BOM NA DISCIPLINA','APRIMORAMENTO','QUALQUER COISA','PROGRAMAÇÃO','ARTICO ACADEMICO','ARTIGO',50,50,1);
SELECT * FROM DISCIPLINA

-- 6. CRIE DOIS CURSOS 'SI' E 'ADS' (FAÇA ISSO EM APENAS UMA INSTRUCAO)

INSERT INTO CURSO (NOME)
VALUES ('SI'),
('ADS')
SELECT * FROM CURSO

-- 7. OFERECA TODAS AS DISCIPLINAS EM TODOS OS CURSOS (FAÇA ISSO USANDO INSERT COM SELECT)
	-- DICA: SELECT * FROM CURSO, DISCIPLINA RETORNA O PRODUTO CARTESIANO DAS DUAS RELAÇÕES
	-- DICA2: O SELECT ABAIXO UTILIZA ROW_NUMBER PARA TRAZER O NRO DE CADA LINHA (PODE SER UTIL)
		--SELECT ROW_NUMBER() OVER(ORDER BY TABLE_NAME),--
		--	TABLE_NAME 
		--FROM INFORMATION_SCHEMA.TABLES

INSERT INTO DISCIPLINA_OFERTADA(ID_COORDENADOR, DT_INICIO_MATRICULA, DT_FIM_MATRICULA, ID_DISCIPLINA, ID_CURSO, ANO , SEMESTRE , TURMA, ID_PROFESSOR , METODOLOGIA, RECURSOS, CRITERIO_AVALIACAO, PLANO_DE_AULAS)
VALUES	(1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 1), 2,2019,2, 'B',1, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO'),
		(1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 1), 3,2019,2, 'C',1, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO'),
		(1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 2), 1,2019,2, 'D',1, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO'),
	    (1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 2), 2,2019,2, 'E',1, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO'),
	    (1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 2), 3,2019,2, 'F',1, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO'),
	    (1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 3), 1,2019,2, 'G',2, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO'),
	    (1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 3), 2,2019,2, 'H',2, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO'),
	    (1, GETDATE(), '2022-04-05 09:30',(SELECT ID FROM DISCIPLINA WHERE ID = 3), 3,2019,2, 'I',2, 'ENSINO', 'MATERIAIS', 'PROVA', 'LIVRO')
SELECT * FROM DISCIPLINA_OFERTADA
 
SELECT * FROM DISCIPLINA_OFERTADA where id_professor = 2



-- 8. ATUALIZE O PROFESSOR DE TODAS AS DISCIPLINAS OFERTADAS PARA O PROFESSOR CRIADO (EMILIO.MURTA) -- UTILIZE UPDATE COM SUBSELECT

UPDATE DISCIPLINA_OFERTADA SET ID_PROFESSOR = (SELECT ID FROM PROFESSOR WHERE ID_USUARIO = (SELECT ID FROM USUARIO WHERE LOGIN = 'EMILIO.MURTA'))




-- 9. CRIE MAIS 9 ALUNOS (FACA ISSO EM UMA INSTRUCAO APENAS)
-- 10. CRIE UMA SOLICITACAO DE MATRICULA PARA OS PRIMEIROS 5 ALUNOS NO PRIMEIRO CURSO (TODAS AS DISCIPLINAS) -- UTILIZE INSERT COM SELECT
-- 11. CRIE UMA SOLICITACAO DE MATRICULA PARA OS ULTIMOS 5 ALUNOS NO SEGUNDO CURSO (TODAS AS DISCIPLINAS) -- UTILIZE INSERT COM SELECT
	-- DICA: ORDER BY <ALGUMA_COISA> OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY; 
	-- ESSE COMANDO INSERIDO NO FINAL DO SELECT VAI DESPREZAR AS 10 PRIMEIRAS LINHAS E TRARÁ AS PRÓXIMAS 5
-- 12. CRIE 3 ATIVIDADES NOVAS (UMA PARA CADA DISCIPLINA)
-- 13. VINCULE CADA ATIVIDADE EM SUA DISCIPLINA OFERTADA (UMA POR CURSO) E UTILIZANDO O PROFESSOR (EMILIO.MURTA) PARA CADA ATIVIDADE VINCULADA 
		-- DEVERÃO SER GERADAS 2 ATIVIDADES_VINCULADAS PARA CADA ATIVIDADE POIS TEMOS CADA DISCIPLINA OFERTADA EM CADA CURSO EM UM TOTAL DE 2 CURSOS
		-- FACA ESSE PROCESSO MANUALMENTE (SEM UTILIZAR INSERT COM SELECT) -- CUIDADO COM OS IDS, SE ERRAR NA INSERÇÃO FAÇA TRUNCATE DAS TABELAS 
		-- OU DROP E CRIE NOVAMENTE
-- 14. CRIE UMA ENTREGA PARA CADA ALUNO PARA CADA ATIVIDADE (OS ALUNOS QUE ENTREGAREM DEVEM ESTAR MATRICULADOS NA DISCIPLINA OFERTADA)
		-- PODE FAZER MANUALMENTE OU USANDO INSERT COM SELECT
-- 15. INSIRA UMA MENSAGEM DE UM PROFESSOR QUALQUER PARA UM ALUNO QUALQUER -- FACA INSERT MANUAL (SEM INSERT COM SELECT)
-- 16. ATUALIZE AS NOTAS DE TODOS OS ALUNOS QUE O NOME COMEÇA COM A LETRA 'A' PARA 7
-- 17. ATUALIZE A DATA DE INICIO DE TODAS AS DISCIPLINAS OFERTADAS PARA O DIA DE HOJE
-- 18. ATUALIZE A DATA DE FIM DE TODAS AS DISCIPLINAS OFERTADAS PARA O DIA DE HOJE + 7 DIAS
-- 19. CRIE UM SCRIPT PARA APAGAR TODOS OS REGISTROS INSERIDOS EM TODAS AS TABELAS (CUIDADO COM A ORDEM DE EXECUÇÃO POR CONTA DAS FKS)
-- 20. APLIQUE NOVAMENTE TODOS OS PROCEDIMENTOS ANTERIORES ATÉ O PASSO 18 GARANTINDO QUE TERÃO OS MESMOS IDS