CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(100),
	TELEFONE VARCHAR(11),
	CONTATO VARCHAR(100)
);

CREATE TABLE PRODUTO(
	ID_PRODUTO	 INT IDENTITY PRIMARY KEY,
	CODIGO INT,
	NOME VARCHAR(100),
	ESTOQUE INT,
	DESCONTINUADO BIT,
	ID_FORNECEDOR INT FOREIGN KEY
	REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

INSERT INTO FORNECEDOR(NOME, TELEFONE, CONTATO)
VALUES
('DELL', '8888', 'CT_DELL'),
('NIKE', '88888', 'CT_NIKE'),
('COCA COLA', '9999', 'CT_CC')

INSERT INTO PRODUTO (CODIGO, NOME, ESTOQUE, DESCONTINUADO, ID_FORNECEDOR)
VALUES
(1, 'TENIS', 10, 0, 1),(2, 'CAMISETA', 10, 0, 1),
(3, 'COCA LATA', 100, 0, 2), (4, 'COCA KS', 100, 0, 2)

INSERT INTO PRODUTO (CODIGO, NOME, ESTOQUE, DESCONTINUADO, ID_FORNECEDOR)
VALUES
(5, 'GOL', 10, 0, NULL)

SELECT * FROM PRODUTO
SELECT * FROM FORNECEDOR

--SELECT COM FILTRO
SELECT	*
FROM	FORNECEDOR F, PRODUTO P
WHERE	F.ID_FORNECEDOR = P.ID_FORNECEDOR

--INNER JOIN
SELECT		P.CODIGO, P.NOME, P.ESTOQUE,
			F.NOME, F.CONTATO, F.TELEFONE
FROM		PRODUTO P
INNER JOIN	FORNECEDOR F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR

--LEFT JOIN
SELECT		P.CODIGO, P.NOME, P.ESTOQUE,
			F.NOME, F.CONTATO, F.TELEFONE
FROM		PRODUTO P
LEFT JOIN	FORNECEDOR F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR


--RIGHT JOIN
SELECT		P.CODIGO, P.NOME, P.ESTOQUE,
			F.NOME, F.CONTATO, F.TELEFONE
FROM		PRODUTO P
RIGHT JOIN	FORNECEDOR F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR

--FULL JOIN
SELECT		P.CODIGO, P.NOME, P.ESTOQUE,
			F.NOME, F.CONTATO, F.TELEFONE
FROM		PRODUTO P
FULL JOIN	FORNECEDOR F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR

--FULL JOIN IS NULL
SELECT		P.CODIGO, P.NOME, P.ESTOQUE,
			F.NOME, F.CONTATO, F.TELEFONE
FROM		PRODUTO P
FULL JOIN	FORNECEDOR F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR
WHERE P.ID_PRODUTO IS NULL

CREATE TABLE VENDA(
	DT_VENDA DATE,
	ID_PRODUTO INT FOREIGN KEY
	REFERENCES PRODUTO(ID_PRODUTO)
);

INSERT INTO VENDA VALUES (GETDATE(), 3)

SELECT * FROM VENDA

SELECT		P.CODIGO, P.NOME, P.ESTOQUE,
			F.NOME, F.CONTATO, F.TELEFONE,
			V.DT_VENDA
FROM		PRODUTO P
FULL JOIN	FORNECEDOR F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR
FULL JOIN	VENDA V ON P.ID_PRODUTO = V.ID_PRODUTO

